### ISSUE TITLE
[Bug] addAlchemyArray "binding=true" missing features

### ISSUE THREAD

**Issue by JAWSAWN** [legendblade/CraftingHarmonics#107]
The alchemy array for binding should make the circle larger, also shrinking animation should only happen at the end. It happens in the middle of it.

**Comment by legendblade** [comment]
I'll look into this, but, at current, we're using Blood Magic's own binding code for this, so, this may not be something that can be easily resolved.

**Comment by legendblade** [comment]
It looks like Blood Magic has a special circle renderer when doing binding; I've switched it over to use the same renderer when you specify isBinding: true; however, this will mean that custom circle graphics can't be used.
