### ISSUE TITLE
Sponge Compatabiliity

### ISSUE THREAD

**Issue by Mohron** [legendblade/CraftingHarmonics#109]
Version: craftingharmonics-1.9.4-1.4.6.29
Also Installed: spongeforge-1.9.4-1954-5.0.0-BETA-1436

When starting a server with sponge and Crafting Harmonics, the server fails to start without crashing.  Will Crafting Harmonics be made compatible with sponge? I do hope so because Crafting Harmonics brings capabilities that cannot be found in another 1.9.4 mod!

Server Log: http://pastebin.com/udf8Rg1a

**Comment by Aaron1011** [comment]
@legendblade: Your `IFMLLoadingPlugin` is implementing `DummyModContainer` [here](https://github.com/legendblade/CraftingHarmonics/blob/276f693a3602ed374939e6c31f752d89156ffa8b/src/main/java/org/winterblade/minecraft/harmony/asm/HarmonyPreloader.java#L17). This causes `DummyModContainer` to be classloaded much earlier than it should, preventing Sponge from transforming it.

Is there any reason why you need your `IFMLLoadingPlugin` to also be a `DummyModContainer`? You should be able to accomplish all of that from your main mod class, which will allow for compatibility ith Sponge.

**Comment by legendblade** [comment]
Sorry, I was using example code for other core mods, so, this problem will probably pop up with those mods as well (at the very least, Season API).  I'll put up some fixed code and hopefully a new release shortly to fix the issue.

**Comment by legendblade** [comment]
@Mohron please let me know if this doesn't resolve the issue.

Thanks. :)
