### ISSUE TITLE
Ability to disable placing/using an item

### ISSUE THREAD

**Issue by legendblade** [legendblade/CraftingHarmonics#121]
This needs research to find the best method to properly affect all targeted items/blocks.

**Comment by legendblade** [comment]
See https://github.com/dexman545/DarkserverUtils/blob/master/main/java/com/failmelon/darkserverutils/events/BlockEvents.java for reference on the two events necessary for this.

**Comment by legendblade** [comment]
This system should ideally use the matcher system.

**Comment by Thiana** [comment]
Would this allow for redirecting what is placed/used? ie, if they try place glowstone at y<50 have it place something like clay instead?

**Comment by legendblade** [comment]
That wasn't a plan for this feature (which is done and coded :P).  I could see adding a separate operation to replace which block was used, though.
