### ISSUE TITLE
Add drops to tallgrass.

### ISSUE THREAD

**Issue by Thiana** [legendblade/CraftingHarmonics#125]
Could you please add functionality to add items to the grass drop table? setBlockDrops doesnt work since it apparently uses it's own table (via http://minecraftforgetutorials.weebly.com/grass-hooks.html). 

With matchers (biome/scoreboard specifically) would be ideal, but even a straight add would be fine.

Thank you :)

PS: How hard would it be to add the ability to remove an item from the player if they die? And in such a way that grave mods don't save it.

**Comment by legendblade** [comment]
Tall grass drops... sounds like fun... I'll take a look at it - honestly may just see if I can force setBlockDrops to work for that as well, as that'd probably be easier than writing an entirely new set of things that work with matchers, that handle items, etc, etc.  :)

Regarding removing an item from a player when they die: in theory setMobDrops can do that, with the includePlayerDrops flag... it's just the fact of if the graves mod ends up picking up the drop prior to my code running:

```
                {
                    type: "setMobDrops",
                    what: ["net.minecraft.entity.EntityPlayerMP"],
                    replace: false,
                    includePlayerDrops: true,
                    remove: [ "minecraft:rotten_flesh" ]
                },
```

**Comment by Thiana** [comment]
Support in setBlockDrops would be nicer :) Simplifies the generation of the configs.

Unfortunately the grave mod I have in the pack is saving the inventory before the item is removed. Though I think I can emulate it by setting a scoreboard on death and then check for it with an addEntityEvent, which would do the actual remove.

**Comment by legendblade** [comment]
So... I'm thinking you may have another mod compatibility issue...

I just spent ~45 minutes adding in another system that would allow me to hook into the grass drops... only to go in and write the config file to set the block drops of minecraft:tallgrass... and it drops the new items no problem.  :-/

**Comment by legendblade** [comment]
Just to clarify, I needed to add in that separate system anyway, so, even if this turns out to be a compat issue, it's still time I needed to spend. :)

**Comment by Thiana** [comment]
Actually it was user error not a mod conflict :( I had a repeatable BQ quest set to OR instead of AND, so it was checking for dimension 2 *or* resourcefulcrops:ItemSeed. Since the item I was dropping from grass is resourcefulcrops:ItemSeed:37, BQ then silently ate the seeds :/ Sorry about the partially wasted time... If I run into something like this again I'll check that I actually can't do what I need in an instance with just CH before I bug you.

The most annoying part is that the quest was one I was going to remove anyway since it's cleaner and simpler to use setBlockDrops now that inDimension is available.

**Comment by legendblade** [comment]
No problem; like I said, I needed to look into this anyway, because it'll allow me to remove the core-mod portion of the mod while still doing coremod-like things (Sponge's Mixin system), so, it's all good.
