### ISSUE TITLE
getResourceLocator

### ISSUE THREAD

**Issue by Thiana** [legendblade/CraftingHarmonics#126]
With getResourceLocator, could you please log the item name as well. Coming back to the log later doesn't always help with mods using ids like 'substratum:ingot:9'. 

Thanks.

**Comment by legendblade** [comment]
So, I'd already planned on overhauling the whole getResourceLocator / getHeldNbt commands into a single command that gives you all the information you'd need in one go (pre-formatted into a JSON object)... but this got me thinking that I should probably still leave in the existing commands as well, and add the localized name in as well.

**Comment by Thiana** [comment]
Thanks :)

The ability to do a full export would be nice. For items with NBT the single command is very useful but when I just want ids it's rather tedious to run the command a dozen times over. I miss NEI's export feature :(
