### ISSUE TITLE
New matcher for Armor points

### ISSUE THREAD

**Issue by Thiana** [legendblade/CraftingHarmonics#127]
I've been testing a new mod (RoughMobs) which increases the chances of random armor on mobs. As a consequence there is a lot more variety, which means checking for specific items like leather vs diamond isnt as useful for drop chances. I also intend to add MekanismTools when it's released which will add even more random armor possibilities.

Could you please consider a new matcher using `net.minecraft.entity.EntityLivingBase#getTotalArmorValue` so I can test for the total armor value regardless of how mixed up the mob's set is?

Thank you.

**Comment by legendblade** [comment]
armorValueRange/isAtArmorValue, then?

**Comment by Thiana** [comment]
What about armor(Min/Max/Range)? I not sure that isArmorValue would be particularly useful. If I were testing for an exact value I'd be testing for specific armor (ie, full diamond/etc). These matchers are for the generic how well armored is the mob.
```
armorMin: 8
armorMax: 5
armorRange: {min: 3, max: 8}
```
