### ISSUE TITLE
No valid sets listed

### ISSUE THREAD

**Issue by elwooha6** [legendblade/CraftingHarmonics#129]
So I have been setting up a set for a couple days, testing as I go, and today I added a recipe involving a knife from Actually Additions and now the set doesn't load and is not listed as a valid set.

Here is a pastebin to my set json, have I done something not allowed or is Actually Additions not supported?

http://pastebin.com/QZWshYtm

~Six

**Comment by legendblade** [comment]
That's... very strange, as I just tested this in a new 1.10 instance with Crafting Harmonics and Actually Additions, and it's working fine with your config file - it properly removes the bread recipe, adds the new torches, etc.  :frowning: 

Is there any error coming up in your console log?

Thanks.

**Comment by elwooha6** [comment]
That's weird, I just tried it in a fresh instance and it worked there too. More testing is needed I think, brb...
