### ISSUE TITLE
JEI 'hide' / 'show' issues

### ISSUE THREAD

**Issue by legendblade** [legendblade/CraftingHarmonics#138]
There are currently two issues with the JEI implementation:

- The 'show' operation overwrites the 'hide' operation.
- The JEI registry only becomes available after the operations actually fire.

**Comment by ConnorRowe** [comment]
Hi, I am still having this issue on the latest version. Here is my default configuration and my latest log: [http://pastebin.com/isifghSn](http://pastebin.com/isifghSn)
[fml-client-latest.log.txt](https://github.com/legendblade/CraftingHarmonics/files/344991/fml-client-latest.log.txt)

**Comment by legendblade** [comment]
@ConnorRowe is the JEI 'hide' part the only issue that you're having with the config, though?

**Comment by ConnorRowe** [comment]
@legendblade Yes, everything else in the config works fine.
