### ISSUE TITLE
Add TechReborn integration

### ISSUE THREAD

**Issue by legendblade** [legendblade/CraftingHarmonics#14]
Add the ability to add/remove TechReborn recipes for its various machines.

See: https://github.com/TechReborn/TechReborn/tree/1.9/src/main/java/techreborn/api/recipe/machines
And: https://github.com/TechReborn/RebornCore/blob/1.9/src/main/java/reborncore/api/recipe/RecipeHandler.java

**Comment by legendblade** [comment]
This could prove difficult due to TiCon and TechReborn using different mappings and utilizing the same fields.

**Comment by legendblade** [comment]
Putting this on hold until TechReborn updates their mappings.

**Comment by ProfessorProspector** [comment]
Hello, one of the TechReborn developers here. Have the mappings been updated since you last checked? I'm not entirely sure.

**Comment by legendblade** [comment]
@ProfessorProspector it does look like the mappings were just updated to a more recent version, so, I'll take a look at it first thing in the morning - last time, unfortunately, I was having some issues getting both TechReborn and Tinker's Construct to play nicely in the same dev environment since they were on a later mapping, and MCP had changed some values around.

Regarding if the integration is better on my end or yours: I would normally be more than happy with your team adding integration on your end, but, I have a feeling the Crafting Harmonics API isn't stable enough at this point.  While I don't forsee too many breaking changes, I think I'd need to get things into a more stable API before having too many other mods provide direct support.

That said, if TechReborn were to add in an easy way to remove already registered recipes, that would make things on my end a lot easier (and require less reflection).

Thanks. :)

**Comment by ProfessorProspector** [comment]
We already have native minetweaker support, might check how that is done, should be in our compat package

**Comment by legendblade** [comment]
Ah, got it.  Your RecipeHandler.recipeList is just a direct reference to the internal recipe list, rather than an immutable copy like a lot of other mods do.  That works.  

Thanks again.

**Comment by modmuss50** [comment]
We have updated to the newest mapping and rb version of forge, if you need help just ask

**Comment by legendblade** [comment]
@modmuss50 Thanks.  I seem to have the basics down, I just have to spend some time studying the existing recipes. :)

**Comment by ProfessorProspector** [comment]
woo, nice ;)
