### ISSUE TITLE
[1.10.2] No Wither skeletons spawning

### ISSUE THREAD

**Issue by tommyTT** [legendblade/CraftingHarmonics#144]
After searching in the nether for half an hour I decided to test it in a creative world with a minimal set of mods installed (version 1.5.3.38, but also tested with 1.5.2.37). It is not possible to spawn in a wither skeleton through a spawn egg in the nether. Going back to version 1.5.1.36 works as expected.

Minecraft 1.10.2
Forge 12.18.0.2006
Mods:
  craftingharmonics-1.9.4_1.10_1.10.2-1.5.3.38
  jei_1.10.2-3.7.3.222
  NashornLib-1.9.4-1.8.77-1.3.1.8

http://paste.ee/p/SMoId

**Comment by legendblade** [comment]
This is due to the same issue as the Ender Dragon from the last bug.  Dangit Mojang.
