### ISSUE TITLE
Scoreboard defaultValue is ignored on scoreboards that dont exist

### ISSUE THREAD

**Issue by Thiana** [legendblade/CraftingHarmonics#145]
With `isScore: { name: scoreboard, value:0, defaultValue: 0 }` the matcher will always return false if the scoreboard does not already exist. That's not expected behavior since the defaultValue should override. 

Thanks :)

**Comment by legendblade** [comment]
Update https://github.com/legendblade/CraftingHarmonics/blob/master/src/main/java/org/winterblade/minecraft/harmony/common/matchers/BaseScoreboardMatcher.java#L49-L50 in order to create the objective if it doesn't exist and isCreate is flagged.
