### ISSUE TITLE
Add Roots integration

### ISSUE THREAD

**Issue by JAWSAWN** [legendblade/CraftingHarmonics#147]
The activities:
* Mortar and Pestle Crafting
* Imbuer Crafting
* Casting Altar Crafting

**Comment by legendblade** [comment]
@Thiana I know you're also working with Roots; was there any other things you'd like to see added along with the above?

Thanks.

**Comment by legendblade** [comment]
@JAWSAWN unfortunately, with the way Roots is coded, I won't be able to do either the Mortal and Pestle crafting or the Imbuer crafting, as the Mortar and Pestle are coded to only output things that are petal dusts, and the Imbuer is likewise coded to only accept petal dusts / sticks.

I do have ritual crafting done, however.

**Comment by Thiana** [comment]
I'd like to be able to modify the number of charges per staff type and modify the cost of a cast with the permanent staff. If that isn't possible, can the mortar crafting be set to allow/disallow crafting of particular dusts? ie, disable the petal dust until they reach a particular progression point. Thanks.

**Comment by legendblade** [comment]
In regards to charges: 
https://github.com/RootsTeam/Roots/blob/master/src/main/java/elucent/roots/item/ItemStaff.java#L186

It looks like the regular staff gets a set number of charges regardless of what spell is being placed on it, so, to fix that, I'd either have to (off the top of my head):
- Hook into their item creation methods
- Scan inventories and update unused staves to the proper use counts.

Neither of which are exactly 'great' ways of going about it.

In regards to costs: There is an 'xpCost' per component (spell), which is then translated to being a mana cost.  Is that what you'd want to change for the crystal staff?

**Comment by legendblade** [comment]
@Thiana thoughts on this?

```
                {
                    // A list of components can be found at:
                    // https://github.com/RootsTeam/Roots/blob/master/src/main/java/elucent/roots/component/ComponentManager.java#L52-L166
                    type: "Roots.removeDust",
                    what: "dandelion"
                },
                {
                    // Make Rose's Thorns cost quite a bit more:
                    type: "Roots.setSpellCost",
                    what: "rosebush",
                    cost: 20 // About half a mana bar
                }
```

**Comment by Thiana** [comment]
If there is a corresponding 'Roots.addDust' operation that would work. Even better would be the ability to alter the crafting cost. Something like: 
```
{
  type: "Roots.addDust",
  what: "dandelion",
  reagents: [ dustGold, imbuedDandelion, dustBlaze, ... ]
}
```
That would also solve the problem of not being able to alter the cast count of basic staves since I can increase the up front cost for them. Not quite as good as being able to alter the cast count directly but acceptable since I can gate the higher tier spells behind other things like a T4 blood altar reagent recipe.

setSpellCost is good :) Basically I want to stop them being able to spam unbalancing spells (as DW20 is currently demonstrating so well with the accel staff ;) without incurring a greater cost than just mana/food.

Thanks :)

**Comment by legendblade** [comment]
@Thiana updating 'Roots.removeDust' to be 'Roots.disableDust' (well... technically Roots.removeDust still works, but it's an alias) and adding in a respective 'Roots.enableDust' operation as well (though you could also just remove the set that Roots.disableDust is in to have a similar effect).  Just... try not to get too fancy with it, as I didn't create a proper stack for enabling/disabling them, so, trying to layer multiple sets with it might start to get... awkward and end up with the wrong result.

In addition, there's now:
```
                {
                    // You can also change the reagents used in a dust; there must be at least 3 reagents used:
                    type: "Roots.setReagents",
                    what: "rosebush",
                    reagents: ["minecraft:diamond","minecraft:string","minecraft:diamond_sword"]
                }
```

**Comment by Thiana** [comment]
I won't need multiple reagent sets for a single dust, so that's perfect. Thank you :)
