### ISSUE TITLE
apply/removeSet messages

### ISSUE THREAD

**Issue by Thiana** [legendblade/CraftingHarmonics#36]
Hi again,

Could we possibly have another command to silence the <setname> [applied|removed] message? I'm using BetterQuesting to dynamically apply/remove sets which has two problems with the current implementation.
(a) It tells the player which ruleset is applied so unless I chose horrible names they're going to get a general idea of what the ruleset does, something I want to avoid in most circumstances
(b) It can get a little spammy when multiple sets are applied/removed in succession.

If possible, it would be nicer if the silence was per set not for the entire mod.

Thank you :)

**Comment by legendblade** [comment]
Just to make sure I understand everything involved (I've been meaning to check out BetterQuesting, but, haven't had the time just yet): when it applies the command, does it actually print out the command it's running, or is this just a matter of the console log being spammed with all the logging for each set?

**Comment by Thiana** [comment]
BetterQuesting has an option to execute the command (ie, /ch applySet name) silently but CH then prints 'name applied' or 'name removed' to the *chatbox*. Thats the part I want to supress. Outputting a message in the log would be fine.

So currently, switching from iron to gold level drops prints 'dropsIronLevel removed' and 'dropsGoldLevel applied' in the chatbox.

**Comment by legendblade** [comment]
Aha.  Alright.  That makes sense.  That should be a lot easier than what I was imagining I was going to have to do. :)

Thanks.
