### ISSUE TITLE
Add block drop configuration operations

### ISSUE THREAD

**Issue by legendblade** [legendblade/CraftingHarmonics#42]
Add a way to configure/override block drops based on:

Some matchers to consider:
- Tool used (block drops only)
- Held offhand / inventory (block drops only)
- Dimension ID
- Biome
- Biome Tag (temperature/humidity/etc)
- Health (min/max; mob shedding only)
- Light level (min/max)
- Above Block (list of blocks)
- Around mobs (list of mobs, with min/max/distance)
- Around blocks (list of blocks, with min/max/distance)
- Time of day (min/max)
- Moon Phase (if possible)
- Has potion effect (mob shedding only)
- In fluid (if possible, mob shedding only)
- Current Main/offhand (mob shedding only)
- Is Riding (mob shedding only)
- Y level (min/max)
- Is raining
- Is storming
- Tool fortune level (block drops only)
- Split dimension into 'inDimension' and 'notInDimension'.
- Add NBT for 'aroundBlocks' / 'aboveBlocks'
- Add in Seasons API support (didn't realize it was as far along as it was... going to definitely include that in my pack as well now)
- Player's potion effects (block drops only). Ability to define multiple potions.
- Inverse checking for potions **not** on a player.  Same as above.
- BetterQuesting / HQM / Progression: Check if quest/criteria is active/inactive/complete/locked.  Ability to define multiple quests and their status.
- HQM / Progression: Check 'points' (HQM calls them factions, I think?).  Does BQ have a similar abstract point system?  Ability to define multiple pools with min/max ranges.

**Comment by Thiana** [comment]
The biome and possibly the y-level?

**Comment by legendblade** [comment]
I just spent roughly a half hour brainstorming ideas for this and the mob shedding options.  The end product of which is:

- Tool used (block drops only)
- Held offhand / inventory (block drops only)
- Dimension ID
- Biome
- Biome Tag (temperature/humidity/etc)
- Health (min/max; mob shedding only)
- Light level (min/max)
- Above Block (list of blocks)
- Around mobs (list of mobs, with min/max/distance)
- Around blocks (list of blocks, with min/max/distance)
- Time of day (min/max)
- Moon Phase (if possible)
- Has potion effect (mob shedding only)
- In fluid (if possible, mob shedding only)
- Current Main/offhand (mob shedding only)
- Is Riding (mob shedding only)
- Y level (min/max)
- Is raining
- Is storming

Some of these probably won't be available in the first iteration, but, I think that will cover most every situation.  I'll probably revisit mob drops and add some of these to there as well.

**Comment by Thiana** [comment]
For blocks specifically, checking the tool fortune levels and the *player's* potion effects would be nice. And I assume the offhand/inventory check will allow for consuming/damaging the item?

For the list of blocks, will you be allowing nbt checks? ie, near a zombie spawner vs any spawner?

For dimensions/etc perhaps allow black/whitelisting?

I'm not sure if you're planning to allow check conditions based on external mods? For example if https://github.com/EdwinMindcraft/SeasonsAPI is installed we could specify that leaves/wheat/etc drop [x] in winter vs [y] in summer. Though I suspect this should be another issue altogether?

Thanks

**Comment by legendblade** [comment]
All very good ideas.

So:
- Tool fortune level (block drops only)
- Split dimension into 'inDimension' and 'notInDimension'.
- Add NBT for 'aroundBlocks' / 'aboveBlocks'
- Add in Seasons API support (didn't realize it was as far along as it was... going to definitely include that in my pack as well now)

Were there any other mods you think there should be checks for, either for block drops, shedding, or even mob drops?

Thanks.

**Comment by Thiana** [comment]
(1) Hooks into the quest mods (BQ/HQM) would be nice. ie, check if quest [id] is inactive/active/complete. I'm doing those 'checks' now with apply/removeSet but a direct check would simplify things.

There are a few other mods but they arent updated to 1.9 yet and I've not seen anything from the authors saying they are porting.

(2) You didn't mention checking  player potion effects so my specific use case... Initially the player is dependent on 'Blessings' (ie, potion effects) from various deities. Only one Blessing can be active at a time, and each of them gives a different advantage. ie, one allows more 'earth' resources like metals another allows 'life' resources like trees/crops, a third more eyes/bones/etc. And then later as they 'abandon' their deities by going into tech the 'Blessing' would become a 'Curse' to drop resources lower requiring mass production/farming to feed tech that doubles/triples/etc resources.

(3) I can see uses for most of the new conditions you listed above in adjusting mobdrops...

**Comment by legendblade** [comment]
Ack, yes, sorry.  Was replying while on a work-related conference call, so, I was a little bit distracted. :)

- Player's potion effects (block drops only). Ability to define multiple potions.
- BetterQuesting / HQM / Progression: Check if quest/criteria is active/inactive/complete/locked.  Ability to define multiple quests and their status.
- HQM / Progression: Check 'points' (HQM calls them factions, I think?).  Does BQ have a similar abstract point system?  Ability to define multiple pools with min/max ranges.

**Comment by Thiana** [comment]
BQ doesnt have a faction system at the moment, though I've requested it be added to the standard pack Funwayguy/StandardQuestingPack#10.

Initially I though I could simulate it with the minecraft scoreboard system but doing a bit more research it looks like I cant :/

**Comment by legendblade** [comment]
Ahh.  Alright.  So, I'll keep in mind that it's a potential future extension point for them.

That also brings up the fact that I should probably add in a way to check a given scoreboard for a player for block/mob drops?

**Comment by legendblade** [comment]
Closed in e65a985 (since I forgot to update the merge message before pushing it...)
