### ISSUE TITLE
Add operation to add potion effects to entities while a set is active

### ISSUE THREAD

**Issue by legendblade** [legendblade/CraftingHarmonics#61]
The ideal solution would:

- Allow you to specify the effect
- Allow you to specify a list of matchers to match on various conditions (almost all mob shed matchers should work)

**Comment by Thiana** [comment]
So the effect will remain on the entity as long as the conditions are true? Or are they only tested when the set is applied?

**Comment by legendblade** [comment]
I was originally going with just being tested when the set was applied, but realized that was a weak implementation, instead, they'll act basically exactly like mob sheds where they're tested every N seconds (which will be another config setting), and you can apply a duration to it if you want.

I figure that way you can either have a potion effect on the player for the entire duration the set is applied, or you can apply it for an amount of time based on a given set of conditions.

**Comment by Thiana** [comment]
And I just realized this will simplify things for me again. I can tie the Curses/Blessings directly to the scoreboard value for that deity and not have to worry about resetting quests in the right order :) Time to rearrange my flowchart again.

**Comment by legendblade** [comment]
And here I was thinking it could just be used to randomly apply regen 3 to every hostile creature on the map during specific times, since you mentioned Blood N' Bones earlier. :)

**Comment by Thiana** [comment]
Uh, no I'm not that nice. The more they kill mobs that spawn in a chunk the stronger but less frequent the following mobs get. So they wont know if that cute little skeleton is going to one shot them or not unless they see where it spawned and have been keeping track of how many spawned there.

Eventually though the chunk will stop spawning mobs for a certain amount of time, or even permanently. Basically its the anti mobfarm measure plus allowing a safe area to build in.

**Comment by legendblade** [comment]
I really like that approach.  I may have to... borrow it if/when I get around to making my own pack.

I suppose I should mention that I'm also planning on taking a crack at mob spawn controls at some point in the future...

**Comment by Thiana** [comment]
And suddenly the apply regen 3 randomly makes sense :)

Hmm, what sort of controls? I'd assume at least health/potion effects on them?

**Comment by Thiana** [comment]
And now I'm having evil ideas again. Dynamically altering spawns so just before sunrise the mobs start spawning with a high chance of a helmet ;)

**Comment by legendblade** [comment]
It's still only a half baked idea, but, the general thought was something akin to how Peaceful Surface lets you control, say, "Only allow hostile mobs to spawn at light level 1 or lower", or "Allow this type of mob to spawn when raining"... just... with all the functionality of the matcher system, and the option to either replace all spawns, or just add the chance of new ones.

But now that you mention it, it would also probably make sense to have some form of "onSpawn" callback, so that you could, as you mention, add potion effects and equipment (+ named mobs?) and things like that.

**Comment by Thiana** [comment]
Oh and feel free to borrow the initial idea. I'd be interested in seeing how you improve it since you seem to do that with all my ideas :)

**Comment by Thiana** [comment]
I can see some nice uses of the adding spawns with matchers involved. It could be used in some interesting ways like causing increasingly large hoards to spawn for a certain amount of time until conditions are met.

**Comment by Thiana** [comment]
Hmm though now I'm wondering, how do I specify *any* mob for aroundMobs rather than a specific type? For a horde type scenario a mob cap would definitely be needed.

**Comment by legendblade** [comment]
Checks if there are 30 mobs within 15 yards:
```
aroundMobs: { what: [], min: 30, dist: 15 }
```

Mind you, this would also check all peaceful mobs as well, so, I may have to extend the aroundMob commands to have an optional flag to say if the matched mobs should be "hostile", "peaceful" or "player" type.

**Comment by Thiana** [comment]
Actually I rather like the idea of being able to change the spawnable light levels dynamically. It could be used to slowly ramp up the difficulty. ie, at first they get normal spawns but the longer they are in that world/area the more things notice them and come looking for them. Slowly raising the light level they spawn at would simulate that effect nicely.

**Comment by legendblade** [comment]
Hrm.  Yeah.  But, that brings up the problem of how you determine if the player's been in a particular area for an amount of time, and then controlling the spawns only in that area.  Per world wouldn't be too bad, but, doing it on a finer grained control than that could prove a little more difficult under the current system.

**Comment by Thiana** [comment]
You could do it indirectly. ie, reset the set progression to the beginning when they find something in world (in my case it would be when they activate another shrine).

**Comment by Thiana** [comment]
Or have it just be an ongoing cycle. ie, every 10 days it moves to the next set, when it reaches set n, it resets to set 1.
