### ISSUE TITLE
Score Matcher Improvements

### ISSUE THREAD

**Issue by legendblade** [legendblade/CraftingHarmonics#78]
For additional support, add in the following:

```
isScore: { name: "foo", player: "bar", value: n }
```

As well as adding an optional "player" parameter to existing score trackers to allow users to check to see if a 'dummy' player has a particular stat.

The following should be available:
- No value specified: The current player being checked.
- A specified player name: Check that player
- "ALL": Ensure all players in the scoreboard have the value.
- "ALLONLINE": Ensure all online players have the value.
- "ANY": Ensure that at least one player on the scoreboard has the value.
- "ANYONLINE": Ensure that at least one player online has the value.

**Comment by Thiana** [comment]
That works even better. Bypasses the need for additional scoreboards as locks.

Thank you :)
